#!/usr/bin/env bash

COPTS=""

function f00() {
  name=$1
  echo $name
  cd $name
  gcc $COPTS ${name}.s
  ./a.out
  echo exit code: $?
  echo
  cd ..
}

COPTS="-nostdlib" f00 00_exit
COPTS="-nostdlib" f00 01_write
f00 00_normal_exit
